/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args){
        OshiMethod oshi = new OshiMethod();
        oshi.printSystemSpecifics();
    }
}
