/*
 * This source file was generated by the Gradle 'init' task
 */

import javax.swing.*;
import java.awt.*;

public class App {
    public static void main(String[] args) {

        MainMenuFrame mainMenuFrame = new MainMenuFrame();
        mainMenuFrame.setVisible(true);

    }
}

abstract class AbstractSystemInfoFrame extends JFrame {
    Color backgroundColor = Color.decode("#211832"); // Background Colour
    Color textColor = Color.decode("#FFFFFF"); // Text Colour
    int windowWidth = 1200;
    int windowHeight = 800;

    protected AbstractSystemInfoFrame(){
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(windowWidth, windowHeight);
        setLayout(null); // using no layout manager
        getContentPane().setBackground(backgroundColor); // set background color
    }
}

class MainMenuFrame extends AbstractSystemInfoFrame {

    public MainMenuFrame() {

        super();

        // Buttons
        JButton[] selectMenuButtons = {
                new JButton("CPU"),
                new JButton("Graphics"),
                new JButton("Memory"),
                new JButton("Disks"),
                new JButton("Network"),
                new JButton("USB Devices"),
                new JButton("PCI Devices")
        };

        int buttonDownShift = 220; // Y-Position of Top Button
        for (JButton button : selectMenuButtons) {
            button.setBounds(480, buttonDownShift, 200, 50);
            buttonDownShift += 50; // Moves down Y-Position for Next Button
            add(button);
        }

        // OS Logo
        ImageIcon icon = new ImageIcon("assets/iconWindows11.png");
        JLabel osLogo = new JLabel(icon);
        osLogo.setBounds(550, 80, 50, 50);
        add(osLogo);
    }


}

